server:
  port: 8031

spring:
  application:
    name: CloudConfigServer
  cloud:
    config:
      server:
        git:
          uri: D:\\test\\Microservices-Course\\spring-cloud-config-server\\git-config